// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pastes.sql

package db

import (
	"context"
)

const getPaste = `-- name: GetPaste :one
SELECT id, user_id, title, content, is_public, expires_at, created_at, updated_at FROM pastes WHERE id = ? LIMIT 1
`

func (q *Queries) GetPaste(ctx context.Context, id string) (Paste, error) {
	row := q.db.QueryRowContext(ctx, getPaste, id)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
