// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shared_pastes.sql

package db

import (
	"context"
)

const getSharedPaste = `-- name: GetSharedPaste :one
SELECT id, paste_id, shared_with, permission FROM shared_pastes WHERE id = ? LIMIT 1
`

func (q *Queries) GetSharedPaste(ctx context.Context, id int64) (SharedPaste, error) {
	row := q.db.QueryRowContext(ctx, getSharedPaste, id)
	var i SharedPaste
	err := row.Scan(
		&i.ID,
		&i.PasteID,
		&i.SharedWith,
		&i.Permission,
	)
	return i, err
}
